FROM ubuntu

ARG basepath=/usr/local/dtc
ARG confpath=/etc/dtc
ARG logpath=/var/log/dtc

RUN mkdir -p $basepath
RUN mkdir -p $basepath/data
RUN mkdir -p $basepath/stat
RUN mkdir -p $basepath/log
RUN mkdir -p $confpath
RUN mkdir -p $logpath

COPY core $basepath/core
COPY dtcagent $basepath/dtcagent
COPY dtc $basepath/dtc
COPY async-connector $basepath/async-connector
COPY connector $basepath/connector
COPY data-lifecycle-manager $basepath/data-lifecycle-manager
COPY hwcserver $basepath/hwcserver
COPY librule.so $basepath/librule.so
COPY libsqlparser.so $basepath/libsqlparser.so

COPY librule.so /usr/local/lib/librule.so
COPY libsqlparser.so /usr/local/lib/libsqlparser.so

RUN apt update
RUN apt install -y iputils-ping net-tools wget

RUN wget "https://dlcdn.apache.org/shardingsphere/5.1.2/apache-shardingsphere-5.1.2-shardingsphere-proxy-bin.tar.gz" -O $basepath/sharding.tar.gz
RUN tar -zxvf $basepath/sharding.tar.gz -C $basepath
RUN $basepath/apache-shardingsphere-5.1.2-shardingsphere-proxy-bin $basepath/sharding

COPY run.sh $basepath/run.sh

RUN chmod +x $basepath/core
RUN chmod +x $basepath/dtcagent
RUN chmod +x $basepath/connector
RUN chmod +x $basepath/run.sh
RUN chmod +x $basepath/async-connector

ENV LD_LIBRARY_PATH=:/usr/local/lib

CMD ["/usr/local/dtc/run.sh"]

#COPY dtc.yaml $confpath/dtc.yaml
#COPY log4cplus.conf $confpath/log4cplus.conf
