FROM ubuntu

ARG basepath=/usr/local/dtc
ARG confpath=/etc/dtc
ARG logpath=/var/log/dtc

RUN mkdir -p $basepath
RUN mkdir -p $basepath/data
RUN mkdir -p $basepath/stat
RUN mkdir -p $basepath/log
RUN mkdir -p $confpath
RUN mkdir -p $logpath

COPY dtcd $basepath/dtcd
COPY dtcagent $basepath/dtcagent
COPY agent-watchdog $basepath/agent-watchdog
COPY async-connector $basepath/async-connector
COPY connector $basepath/connector
COPY librule.so $basepath/librule.so
COPY data-lifecycle-manager $basepath/data-lifecycle-manager
COPY hwcserver $basepath/hwcserver

RUN apt update
RUN apt install -y iputils-ping
RUN apt install -y net-tools

COPY run.sh $basepath/run.sh

RUN chmod +x $basepath/dtcd
RUN chmod +x $basepath/dtcagent
RUN chmod +x $basepath/connector
RUN chmod +x $basepath/run.sh

CMD ["./usr/local/dtc/run.sh dtc"]

#COPY dtc.yaml $confpath/dtc.yaml
#COPY log4cplus.conf $confpath/log4cplus.conf
