FROM ubuntu

ARG basepath=/usr/local/dtc
ARG confpath=/etc/dtc
ARG logpath=/var/log/dtc

RUN mkdir -p $basepath
RUN mkdir -p $basepath/data
RUN mkdir -p $basepath/stat
RUN mkdir -p $basepath/log
RUN mkdir -p $confpath
RUN mkdir -p $logpath

COPY dtcd $basepath/dtcd
COPY dtcagent $basepath/dtcagent
COPY agent-watchdog $basepath/agent-watchdog
COPY async-connector $basepath/async-connector
COPY connector $basepath/connector
COPY data-lifecycle-manager $basepath/data-lifecycle-manager
COPY hwcserver $basepath/hwcserver

RUN chmod +x $basepath/dtcd
RUN chmod +x $basepath/connector

COPY /github/workspace/tests/conf/dtc.yaml $confpath/dtc.yaml
COPY /github/workspace/tests/conf/log4cplus.conf $confpath/log4cplus.conf

#COPY dtc.yaml $confpath/dtc.yaml
#COPY log4cplus.conf $confpath/log4cplus.conf
