FROM centos:centos8

COPY start.sh /root/start.sh

ARG sofile=libdtc.2.so
COPY $sofile /usr/lib/$sofile
RUN ln -sf /usr/lib/$sofile /usr/lib/libdtc.so.1 && \
    ln -sf /usr/lib/libdtc.so.1 /usr/lib/libdtc.so && \
    echo "/usr/lib" >> /etc/ld.so.conf && \
    /sbin/ldconfig -v

#cpp test
RUN mkdir -p /usr/local/sdk-cpp
COPY ../../src/devel/cpp/dtcapi.h /usr/local/sdk-cpp/dtcapi.h
COPY ../../test/get.cc /usr/local/sdk-cpp/get.cc
COPY ../../test/insert.cc /usr/local/sdk-cpp/insert.cc
COPY ../../test/build.sh /usr/local/sdk-cpp/build.sh

CMD ["/bin/bash", "/root/start.sh"]