name: test

on:
  push:
  pull_request:
    
jobs:        
  start-mysql:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        ports:
          - 3306:3306
        env: 
          MYSQL_ROOT_PASSWORD: 123456
    steps:
      - name: Init db table
        run: |
          sleep 10s
          mysql -h127.0.0.1 -uroot -p123456 -e "create database layer2;"
          mysql -h127.0.0.1 -uroot -p123456 -e "show databases;"  
          
  start-dtc:
    runs-on: ubuntu-latest
    container:
      image: docker://docker.io/kfysck/devel:all
      volumes:
        - ${{github.workspace}}/tests/conf:/etc/dtc/
    steps:
    - uses: actions/checkout@v3
        
    - name: before docker
      run: |
        cd ${{github.workspace}}
        mkdir -p tests/conf/
        sudo cp -f conf/log4cplus.conf tests/conf/
        sudo cp -f dockerfiles/devel/dtc.cacheonly.yaml tests/conf/
    
    - name: my docker test
      with:
        entrypoint: /usr/local/dtc/dtcd
        cmd: -d
