name: test

on:
  push:
  pull_request:
    
jobs:        
  build-and-test:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql
        ports:
          - 3306:3306
        env: 
          MYSQL_ROOT_PASSWORD: 123456
        volumes:
          - ${{github.workspace}}/tests/conf/:/etc/dtc/
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Init db table
      run: |
        sleep 10s
        mysql -h127.0.0.1 -uroot -p123456 -e "create database layer2;"
        mysql -h127.0.0.1 -uroot -p123456 -e "show databases;"  
    
    - name: before docker
      run: |
        cd ${{github.workspace}}
        mkdir -p tests/conf/
        cp -f conf/log4cplus.conf tests/conf/ 
        cp -f dockerfiles/devel/dtc.cacheonly.yaml tests/conf/dtc.yaml
    
    - name: my docker test
      uses: docker://docker.io/kfysck/devel:all
      with:
        entrypoint: /usr/local/dtc/dtcd
        cmd: -d
