name: ubuntu-18.04&gcc-4.9

on: pull_request
    
env:
  CC: gcc-4.9
  CXX: g++-4.9

jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v3
    
    - name: install gcc env
      run: |
        echo "deb http://dk.archive.ubuntu.com/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list
        echo "deb http://dk.archive.ubuntu.com/ubuntu/ xenial universe" | sudo tee -a /etc/apt/sources.list
        sudo apt update
        sudo apt install gcc-4.9 g++-4.9
      shell: bash
      
    - name: install dependency
      run: |
        sudo apt-get install -y make zlib1g zlib1g-dev bzip2 liblz4-dev libasan0 openssl libmxml-dev wget

    - name: update hsql
      run: |
        wget https://github.com/DTC8/sql-parser/releases/download/hsql.forked-v1/hsql.forked-v1.tar.gz -O hsql.tar.gz
        tar -zxvf hsql.tar.gz
        cd hsql
        cp -rf include/ ${{github.workspace}}/src/libs/hsql/
        cp -f libs/libsqlparser.so ${{github.workspace}}/src/libs/hsql/libs/libsqlparser.so
        cp -f libs/libsqlparser.a ${{github.workspace}}/src/libs/hsql/libs/libsqlparser.a
      
    - name: cmake project
      run: |
        cd ${{github.workspace}}
        mkdir build
        cd build
        cmake ../
        make
